---
title: "Sensitivity Analysis"
author: "Claudia Flores, Haley Grant, Shuhan Song"
date: "4/16/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE, 
                      message = FALSE)
```

```{r}
## Read in packages
library(tidyverse)
library(janitor)
library(patchwork)
library(purrr)
```

```{r}
## Read in data file 'clim.txt'
climate <- read_table2("data/clim.txt") %>% 
  clean_names() # Clean up column names in climate data frame
```

```{r}
## Aggregating climate data

# Aggregate daily climate data frame into yearly and monthly averages for minimum and maximum temperature observations and sum for precipitation
climate_averages <- climate %>% 
# Grouping the same years and months observations within the year and month column to have results separated out into monthly and yearly results
  group_by(month,year) %>% 
  summarise(
    avg_tmax_c = mean(tmax_c), # Finding the average for maximum temperature
    avg_tmin_c = mean(tmin_c), # Finding the average for minimum temperature
    sum_precip = sum(precip) # Finding the sum for precipitation 
  )

# precipitation averages for first month (P_1)
climate_averages_1 <- climate_averages %>% 
  filter(month == 1) %>% # Filtering the first month for each year
  select(-avg_tmin_c) %>% # Removing the column named avg_tmin_c
  select(-avg_tmax_c) # Removing the column named avg_tmax_c

# minimum temperature averages for second month (Tn_2)
climate_averages_2 <- climate_averages %>% 
  filter(month == 2) %>% # Filtering the first month for each year
  select(year,avg_tmin_c,month) # Keep only two columns: year and avg_tmin_c

# combine the 2 previous data sets
climate_averages_3 <- merge(climate_averages_1,climate_averages_2, by = "year") 
```

```{r}
## Source almond_model.R function into RMarkdown
source("R/almond_model.R")
```

```{r}
## Sampling for sensitivity analysis

# How many simulations
number_runs = 500
# generate data with normal distribution
P_1_2_coeff <- rnorm(mean=0.0043, sd=0.001, n=number_runs)

# Run the model with the data we created along with inputs
# Use map_dfc to run for each value of P_1_2_coeff - where we get results for all Tn_2 and P_1 for each P_1_2_coeff value
res = P_1_2_coeff %>% map_dfc(~almond_model(Tn_2 = climate_averages_3$avg_tmin_c, # input
                                        P_1 = climate_averages_3$sum_precip,
                                        P_1_2_coeff = .x) # function
                          ) # input

# Set column names to actual values
colnames(res) = P_1_2_coeff

# Add year column starting with years 1989 to 2010
res <- res %>% 
  mutate(year = climate_averages_3$year) # years based of original data clim.txt 

# Rearrange using pivot function to plot
resg = as.data.frame(res) %>% # calling data frame
  pivot_longer(!year, # do not use column year to pivot
               names_to = "P_1_2_coeff", 
               values_to = "yield_anomaly_tons_per_acre") 

# Merge data frames
resg_merge = merge(resg, climate_averages_3) %>% 
  rename(sum_precip_month1 = sum_precip,
         avg_tmin_month2_c = avg_tmin_c) %>% 
  select(-month.x, -month.y)
```

```{r}
## Box plot 

# Graph shows yield anomaly by year
ggplot(data = resg_merge,
       aes(x = as.factor(year), 
           y = yield_anomaly_tons_per_acre)) +
  geom_boxplot() +
  labs(x = "Year",
       y = "Yield Anomaly (tons/acre)",
       title = "Sensitivity analysis of almond yield to the second degree of January precipitation") +
  theme_minimal()

ggsave("sens_analysis_boxplot.png") # save boxplot image
```
```{r}
## Source almond_model.R function into RMarkdown
source("R/compute_NPV.R")
```

```{r}
## Assumptions and Conversion and NPV

# Assumptions

# Almond production costs $3800/acre
almond_production_costs = 3800

# Almond profit is $2.50/lb
# Convert 1 lb into metric tons
# 1 Pound = 0.00045359237 Metric Tons
almond_profit = 2.50 * (1/0.00045359237)
almond_profit # $ per metric tons

# Almond production on average is 1 ton/acre/yr
almond_production_avg = 1

# NPV
resg_merge_anom_avg <- resg_merge %>% 
  mutate(anom_plus_avg_yield = resg_merge$yield_anomaly_tons_per_acre + almond_production_avg) # add average of 1 ton/acre/yr to anomaly

resg_merge_net_profit <- resg_merge_anom_avg %>% 
  mutate(almond_production_costs = almond_production_costs) %>% # USe production costs of $3800 per acre for all years
  mutate(almond_profit = resg_merge_anom_avg$anom_plus_avg_yield * almond_profit) %>% # calculate almond profit by multiplying yield anomaly to almond profit 
  mutate(net_profit = almond_profit - almond_production_costs) # calculate net profit by subtracting almond profit to almond production costs

# Use compute_NPV.R function to find NPV for each year
NPV = compute_NPV(resg_merge_net_profit$net_profit, time = (resg_merge_net_profit$year-min(resg_merge_net_profit$year))) # discount net profit to year 1989
head(NPV) # call up the first 5 values of NPV calculations 

# Add NPV values from above to resg_merge_NPV data frame
resg_merge_NPV <- resg_merge_net_profit %>% 
  mutate(NPV = NPV) # add NPV column using NPV values calculated from compute_NPV.R function

```

```{r}
## Box plot 

# Graph shows yield anomaly by year
ggplot(data = resg_merge_NPV,
       aes(x = as.factor(year), 
           y = NPV)) +
  geom_boxplot() +
  labs(x = "Year",
       y = "NPV ($/acre)",
       title = "Sensitivity analysis of NPV to the second degree of January precipitation") +
  theme_minimal()

ggsave("NPV_boxplot.png") # save boxplot image
```